### ISSUE TITLE
Error during automated install >  This integration does not support configuration via the UI. 

### ISSUE THREAD

**Issue by quadcom** [custom-components/sensor.radarr_upcoming_media#37]
**Describe the Bug**
Clicking on the repositories link to install fails with an error:

**The Error**

" This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant. "

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**

I looked through here but didn't find anything

**What data does the sensor display if any?**

Can't get it working

**What displays when visiting the API URL from the troubleshooting guide?**

**Does the default Home Assistant Radarr component work for you?**

**Home Assistant Version**
HAOS > 

Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

FF: 125.0.3 (64-bit)

**Comment by mkanet** [comment]
Hi there, it sounds like your trying to install the really old version of this integration from a couple of years back.  Since the new version of this integration isn't yet available on HACS, you will have to manually add the repo URL to Home Assistant (HACS) like this:

1. Navigate to HACS on Home Assistant
2. Click on the Integrations section of HACS
3. Click on the 3 dots (on the top/right of the screen) and select `Custom Repositories`
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/c4e191ab-679e-4526-b907-6e138db64318)
4. Next, copy and paste `https://github.com/custom-components/sensor.radarr_upcoming_media` into the Repository failed and also select "Integration" for the Category, like this:
![image](https://github.com/custom-components/sensor.radarr_upcoming_media/assets/811008/5e41d9c4-f09a-426b-a143-c318562641cf)
5. Click on **ADD**

After you do that you should see the official Plex Recently Added Integration.  The current version is: **0.4.0**,  If the version says that or newer, then that is the correct repo, otherwise you're adding the really old version version.

Please note after you do this, you will see a warning under HACS like below.  You can click on SHOW, then click IGNORE.  **This will warning should go away as soon as the HACS moderators approve/merge my PR to HACS.**

**Comment by quadcom** [comment]
The repo gets added but going back to the HACS main page, above the restart banner is a notification stating the repo is being removed because it is archived.

![image](https://github.com/custom-components/sensor.radarr_upcoming_media/assets/7085931/b46fedfa-1964-44e9-ad58-5df8f76fa4a5)

![image](https://github.com/custom-components/sensor.radarr_upcoming_media/assets/7085931/cb7c2d11-35f2-422b-abb8-bf2d170bb2aa)


As such nothing is installed once restarting HA.

**Comment by mkanet** [comment]
Hi @quadcom those messages can be ignored.  You only need to click Ignore once.  They are temporary messages; and, will go away once [these PRs](https://github.com/hacs/default/pulls/mkanet) are merged into Home Assistant officially.  Its already been 
over 3 months since I submitted them.  The HACS moderators are probably very busy.  Once they are merged, you wont need to manually add the repo to Home Assistant.

**Comment by quadcom** [comment]
Hey, sorry about that. The ignore button wasn't doing anything visually, the popup stayed where it was. But the repo did stay added after restarting.
